"$schema" = "../../../docs/maa-cli/schemas/task.schema.json"

[[tasks]]
name = "启动 B 服"
type = "StartUp"
params = { client_type = "Bilibili", start_game_enabled = true }

[[tasks]]
name = "领取奖励但跳过邮件"
type = "Award"
[tasks.params]
award = true
mail = false
recruit = true
orundum = true
mining = true
specialaccess = true
