"$schema" = "../../../docs/maa-cli/schemas/task.schema.json"

[[tasks]]
name = "启动 B 服"
type = "StartUp"

[tasks.params]
client_type = "Bilibili"
start_game_enabled = true

[tasks.linux_maa]
id = "startup--b-a5ce8dac"
unlimited_runs = true
important = true
retry_even_success = true

[tasks.linux_maa.managed_params]

[[tasks]]
name = "关闭游戏"
type = "CloseDown"

[tasks.params]
client_type = "Bilibili"
enable = false

[tasks.linux_maa]
id = "closedown-b2541c9a"
unlimited_runs = true
important = true
retry_even_success = true

[tasks.linux_maa.managed_params]
