"$schema" = "../../docs/maa-cli/schemas/cli.schema.json"

[core]
channel = "Stable"
test_time = 0

[core.components]
library = true
resource = true

[cli]
channel = "Stable"

[cli.components]
binary = true

[resource]
auto_update = true
warn_on_update_failure = true
backend = "git"

[resource.remote]
branch = "main"
url = "https://github.com/MaaAssistantArknights/MaaResource.git"
