from linux_maa.settings import (
    BILIGAME_API_URLS,
    DEFAULT_DEVICE_SERIAL,
    DEFAULT_GAME_ID,
    DEFAULT_TARGET_PACKAGE,
    DESKTOP_USER_AGENT,
    MOBILE_USER_AGENT,
)

__all__ = [
    "BILIGAME_API_URLS",
    "DEFAULT_DEVICE_SERIAL",
    "DEFAULT_GAME_ID",
    "DEFAULT_TARGET_PACKAGE",
    "DESKTOP_USER_AGENT",
    "MOBILE_USER_AGENT",
]
